# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

variables:
- name: subscription
  value: '9cc6ba70-2e1a-4749-b09e-630c9e071f42'
- name: rg-name
  value: 'rg-stock'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzurePipeline'
    subscriptionId: $(subscription)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(rg-name)
    location: 'japaneast'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/pekumirui/az-infra-arm/blob/main/azurefuntion.json'
    deploymentMode: 'Incremental'
    deploymentName: 'deployment-azurefuntion'